
import React, { createContext, useState, useEffect, useCallback, useContext } from 'react';

type Theme = 'light' | 'dark';
type Language = 'en' | 'es' | 'eu';

interface AppContextType {
  theme: Theme;
  setTheme: (theme: Theme) => void;
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, replacements?: { [key: string]: string }) => string;
}

const AppContext = createContext<AppContextType | undefined>(undefined);

const translations: { [key in Language]: any } = {
  en: {
    "header.title": "LRA-IDE",
    "header.file": "File",
    "header.edit": "Edit",
    "header.view": "View",
    "header.run": "Run",
    "header.help": "Help",
    "header.analyzing": "Analyzing...",
    "activitybar.explorer": "Explorer",
    "activitybar.search": "Search",
    "activitybar.source_control": "Source Control",
    "activitybar.run_debug": "Run and Debug",
    "activitybar.extensions": "Extensions",
    "activitybar.save_analysis": "Save Analysis Session",
    "sidebar.explorer": "Explorer",
    "sidebar.data_source": "Data Source",
    "sidebar.variables": "Variables",
    "sidebar.plot_button": "Plot Data",
    "uploader.upload_csv": "Upload CSV",
    "uploader.import_analysis": "Import Analysis",
    "uploader.new_table": "New Table",
    "uploader.no_folder": "No folder opened",
    "variables.independent": "Independent Variable (X)",
    "variables.dependent": "Dependent Variable (Y)",
    "main.workspace_title": "Analysis Workspace",
    "main.workspace_description": "Upload a CSV file or import an analysis session to begin.",
    "main.no_data": "No data to display.",
    "main.plot_placeholder_title": "Ready to Plot",
    "main.plot_placeholder_description": "Select your variables and click the 'Plot Data' button in the explorer to visualize your data.",
    "tabs.analysis_fitting": "Analysis & Fitting",
    "tabs.simulation": "Simulation",
    "tabs.close_tab_tooltip": "Close Tab",
    "simulation.title": "Simulation Panel",
    "simulation.description": "The simulation environment will be available here. You will be able to test models and run scenarios against your data.",
    "plot.observations": "Observations",
    "plot.regression_line": "Regression Line",
    "tooltip.residual": "Residual",
    "analysis.show_grid": "Show Grid",
    "analysis.show_line": "Show Regression Line",
    "analysis.show_residuals": "Show Residuals",
    "analysis.show_observations": "Show Observations",
    "analysis.regression_type_title": "Regression Type",
    "analysis.linear_regression": "Linear Regression",
    "analysis.higher_order_regressions": "Higher-Order Regressions",
    "analysis.regression_method_title": "Regression Method",
    "analysis.regression_method_placeholder": "Method options for the selected regression will appear here.",
    "analysis.tab_analysis": "Analysis",
    "analysis.tab_residuals": "Residuals Plot",
    "analysis.residual": "Residual",
    "analysis.residuals": "Residuals",
    "analysis.controls_title": "Analysis Controls",
    "analysis.decimal_points": "Decimal Points",
    "plot_explorer.title": "Plot Explorer",
    "plot_explorer.tab_series": "Series",
    "plot_explorer.tab_plot": "Plot",
    "plot_explorer.tab_export": "Export",
    "plot_explorer.general": "General",
    "plot_explorer.scatter": "Scatter Plot",
    "plot_explorer.regression_line": "Regression Line",
    "plot_explorer.residuals": "Residuals",
    "plot_explorer.color": "Color",
    "plot_explorer.opacity": "Opacity",
    "plot_explorer.size": "Size",
    "plot_explorer.width": "Width",
    "plot_explorer.style": "Style",
    "plot_explorer.style_solid": "Solid",
    "plot_explorer.style_dashed": "Dashed",
    "plot_explorer.style_dotted": "Dotted",
    "plot_explorer.show_legend": "Show Legend",
    "plot_explorer.show_title": "Show Title",
    "plot_explorer.axes_domain": "Axis Domain",
    "plot_explorer.x_min": "X Min",
    "plot_explorer.x_max": "X Max",
    "plot_explorer.y_min": "Y Min",
    "plot_explorer.y_max": "Y Max",
    "plot_explorer.tick_formatting": "Tick Formatting",
    "plot_explorer.sig_figs": "Sig. Figures",
    "plot_exporter.title": "Export Configuration",
    "plot_exporter.filename": "File Name",
    "plot_exporter.format": "Format",
    "plot_exporter.dimensions": "Dimensions",
    "plot_exporter.width": "Width",
    "plot_exporter.height": "Height",
    "plot_exporter.dpi": "Resolution (DPI)",
    "plot_exporter.labels": "Labels",
    "plot_exporter.plot_title": "Plot Title",
    "plot_exporter.x_axis_label": "X-Axis Label",
    "plot_exporter.y_axis_label": "Y-Axis Label",
    "plot_exporter.typography": "Typography",
    "plot_exporter.font_family": "Font Family",
    "plot_exporter.font_size": "Font Size (px)",
    "plot_exporter.theme": "Theme",
    "plot_exporter.theme_current": "Current",
    "plot_exporter.theme_grayscale": "Grayscale",
    "plot_exporter.theme_publication": "Publication",
    "plot_exporter.export_button": "Export",
    "plot_toolbar.pan": "Pan",
    "plot_toolbar.box_select": "Box Select",
    "plot_toolbar.zoom_in": "Zoom In",
    "plot_toolbar.zoom_out": "Zoom Out",
    "plot_toolbar.reset_view": "Reset View",
    "plot_toolbar.clear_selection": "Clear Selection",
    "plot_toolbar.export_plot": "Export Plot as SVG",
    "right_sidebar.equation": "Regression Equation",
    "results.summary": "Summary Statistics",
    "results.rsquared": "R-Squared",
    "results.rsquared_desc": "Model Fit",
    "results.stderr": "Std. Error",
    "results.stderr_desc": "Prediction Error",
    "results.slope": "Slope (β₁)",
    "results.slope_desc": "X's Effect on Y",
    "results.intercept": "Intercept (β₀)",
    "results.intercept_desc": "Y value at X=0",
    "statusbar.ready": "Ready",
    "statusbar.error": "Error",
    "statusbar.rows": "Rows",
    "statusbar.type": "Linear Regression",
    "table.add_row": "Add Row",
    "table.add_column": "Add Column",
    "table.delete_row": "Delete Row",
    "table.delete_column": "Delete Column",
    "table.delete_selected_rows": "Delete Selected Rows",
    "table.new_column_prompt": "Enter new column name:",
    "table.duplicate_column_error": "A column named '{columnName}' already exists.",
    "error.invalid_file_type": "Invalid file type. Please upload a CSV file.",
    "error.not_enough_columns": "CSV file must have at least two columns.",
    "error.no_data_rows": "CSV file contains no valid data rows. Please check the file's content and formatting.",
    "error.parse_failed": "Failed to parse CSV file. Please check its format.",
    "error.import_failed": "Failed to import analysis file. It may be corrupt or in the wrong format.",
    "error.missing_data": "Please select variables before plotting.",
    "error.same_variables": "Independent and dependent variables cannot be the same.",
    "error.analysis_failed": "Analysis failed: {errorMessage}",
    "error.unknown": "An unknown error occurred.",
    "error.not_enough_data": "Not enough valid data points for regression analysis (minimum 2 required).",
    "error.identical_x": "All independent (X) variable values are identical. Cannot compute a unique regression line."
  },
  es: {
    "header.title": "IDE-ALR",
    "header.file": "Archivo",
    "header.edit": "Editar",
    "header.view": "Ver",
    "header.run": "Ejecutar",
    "header.help": "Ayuda",
    "header.analyzing": "Analizando...",
    "activitybar.explorer": "Explorador",
    "activitybar.search": "Buscar",
    "activitybar.source_control": "Control de Fuentes",
    "activitybar.run_debug": "Ejecutar y Depurar",
    "activitybar.extensions": "Extensiones",
    "activitybar.save_analysis": "Guardar Sesión de Análisis",
    "sidebar.explorer": "Explorador",
    "sidebar.data_source": "Fuente de Datos",
    "sidebar.variables": "Variables",
    "sidebar.plot_button": "Graficar Datos",
    "uploader.upload_csv": "Subir CSV",
    "uploader.import_analysis": "Importar Análisis",
    "uploader.new_table": "Nueva Tabla",
    "uploader.no_folder": "Ninguna carpeta abierta",
    "variables.independent": "Variable Independiente (X)",
    "variables.dependent": "Variable Dependiente (Y)",
    "main.workspace_title": "Espacio de Análisis",
    "main.workspace_description": "Sube un archivo CSV o importa una sesión de análisis para comenzar.",
    "main.no_data": "No hay datos para mostrar.",
    "main.plot_placeholder_title": "Listo para Graficar",
    "main.plot_placeholder_description": "Selecciona tus variables y haz clic en el botón 'Graficar Datos' en el explorador para visualizar tus datos.",
    "tabs.analysis_fitting": "Análisis y Ajuste",
    "tabs.simulation": "Simulación",
    "tabs.close_tab_tooltip": "Cerrar Pestaña",
    "simulation.title": "Panel de Simulación",
    "simulation.description": "El entorno de simulación estará disponible aquí. Podrás probar modelos y ejecutar escenarios con tus datos.",
    "plot.observations": "Observaciones",
    "plot.regression_line": "Línea de Regresión",
    "tooltip.residual": "Residuo",
    "analysis.show_grid": "Mostrar Rejilla",
    "analysis.show_line": "Mostrar Línea de Regresión",
    "analysis.show_residuals": "Mostrar Residuos",
    "analysis.show_observations": "Mostrar Observaciones",
    "analysis.regression_type_title": "Tipo de Regresión",
    "analysis.linear_regression": "Regresión Lineal",
    "analysis.higher_order_regressions": "Regresiones de Orden Superior",
    "analysis.regression_method_title": "Método de Regresión",
    "analysis.regression_method_placeholder": "Las opciones del método para la regresión seleccionada aparecerán aquí.",
    "analysis.tab_analysis": "Análisis",
    "analysis.tab_residuals": "Gráfico de Residuos",
    "analysis.residual": "Residuo",
    "analysis.residuals": "Residuos",
    "analysis.controls_title": "Controles de Análisis",
    "analysis.decimal_points": "Puntos Decimales",
    "plot_explorer.title": "Explorador de Gráfico",
    "plot_explorer.tab_series": "Series",
    "plot_explorer.tab_plot": "Gráfico",
    "plot_explorer.tab_export": "Exportar",
    "plot_explorer.general": "General",
    "plot_explorer.scatter": "Gráfico de Dispersión",
    "plot_explorer.regression_line": "Línea de Regresión",
    "plot_explorer.residuals": "Residuos",
    "plot_explorer.color": "Color",
    "plot_explorer.opacity": "Opacidad",
    "plot_explorer.size": "Tamaño",
    "plot_explorer.width": "Ancho",
    "plot_explorer.style": "Estilo",
    "plot_explorer.style_solid": "Sólido",
    "plot_explorer.style_dashed": "Discontinuo",
    "plot_explorer.style_dotted": "Punteado",
    "plot_explorer.show_legend": "Mostrar Leyenda",
    "plot_explorer.show_title": "Mostrar Título",
    "plot_explorer.axes_domain": "Dominio de Ejes",
    "plot_explorer.x_min": "X Mín",
    "plot_explorer.x_max": "X Máx",
    "plot_explorer.y_min": "Y Mín",
    "plot_explorer.y_max": "Y Máx",
    "plot_explorer.tick_formatting": "Formato de Marcas",
    "plot_explorer.sig_figs": "Cifras Sig.",
    "plot_exporter.title": "Configuración de Exportación",
    "plot_exporter.filename": "Nombre de Archivo",
    "plot_exporter.format": "Formato",
    "plot_exporter.dimensions": "Dimensiones",
    "plot_exporter.width": "Ancho",
    "plot_exporter.height": "Alto",
    "plot_exporter.dpi": "Resolución (DPI)",
    "plot_exporter.labels": "Etiquetas",
    "plot_exporter.plot_title": "Título del Gráfico",
    "plot_exporter.x_axis_label": "Etiqueta Eje X",
    "plot_exporter.y_axis_label": "Etiqueta Eje Y",
    "plot_exporter.typography": "Tipografía",
    "plot_exporter.font_family": "Fuente",
    "plot_exporter.font_size": "Tamaño de Fuente (px)",
    "plot_exporter.theme": "Tema",
    "plot_exporter.theme_current": "Actual",
    "plot_exporter.theme_grayscale": "Escala de Grises",
    "plot_exporter.theme_publication": "Publicación",
    "plot_exporter.export_button": "Exportar",
    "plot_toolbar.pan": "Mover",
    "plot_toolbar.box_select": "Selección de Caja",
    "plot_toolbar.zoom_in": "Acercar",
    "plot_toolbar.zoom_out": "Alejar",
    "plot_toolbar.reset_view": "Restablecer Vista",
    "plot_toolbar.clear_selection": "Limpiar Selección",
    "plot_toolbar.export_plot": "Exportar Gráfico como SVG",
    "right_sidebar.equation": "Ecuación de Regresión",
    "results.summary": "Estadísticas de Resumen",
    "results.rsquared": "R-Cuadrado",
    "results.rsquared_desc": "Ajuste del Modelo",
    "results.stderr": "Error Est.",
    "results.stderr_desc": "Error de Predicción",
    "results.slope": "Pendiente (β₁)",
    "results.slope_desc": "Efecto de X en Y",
    "results.intercept": "Intercepto (β₀)",
    "results.intercept_desc": "Valor de Y en X=0",
    "statusbar.ready": "Listo",
    "statusbar.error": "Error",
    "statusbar.rows": "Filas",
    "statusbar.type": "Regresión Lineal",
    "table.add_row": "Añadir Fila",
    "table.add_column": "Añadir Columna",
    "table.delete_row": "Eliminar Fila",
    "table.delete_column": "Eliminar Columna",
    "table.delete_selected_rows": "Eliminar Filas Seleccionadas",
    "table.new_column_prompt": "Introduce el nombre de la nueva columna:",
    "table.duplicate_column_error": "Ya existe una columna llamada '{columnName}'.",
    "error.invalid_file_type": "Tipo de archivo no válido. Por favor, sube un archivo CSV.",
    "error.not_enough_columns": "El archivo CSV debe tener al menos dos columnas.",
    "error.no_data_rows": "El archivo CSV no contiene filas de datos válidas. Revisa el contenido y el formato del archivo.",
    "error.parse_failed": "No se pudo analizar el archivo CSV. Por favor, revisa su formato.",
    "error.import_failed": "No se pudo importar el archivo de análisis. Puede estar corrupto o en el formato incorrecto.",
    "error.missing_data": "Por favor, selecciona las variables antes de graficar.",
    "error.same_variables": "Las variables independiente y dependiente no pueden ser iguales.",
    "error.analysis_failed": "El análisis falló: {errorMessage}",
    "error.unknown": "Ocurrió un error desconocido.",
    "error.not_enough_data": "No hay suficientes puntos de datos válidos para el análisis de regresión (se requieren 2 como mínimo).",
    "error.identical_x": "Todos los valores de la variable independiente (X) son idénticos. No se puede calcular una línea de regresión única."
  },
  eu: {
    "header.title": "LRA-IDE",
    "header.file": "Fitxategia",
    "header.edit": "Editatu",
    "header.view": "Ikusi",
    "header.run": "Exekutatu",
    "header.help": "Laguntza",
    "header.analyzing": "Aztertzen...",
    "activitybar.explorer": "Esploratzailea",
    "activitybar.search": "Bilatu",
    "activitybar.source_control": "Iturburu Kontrola",
    "activitybar.run_debug": "Exekutatu eta Araztu",
    "activitybar.extensions": "Hedapenak",
    "activitybar.save_analysis": "Gorde Analisi Saioa",
    "sidebar.explorer": "Esploratzailea",
    "sidebar.data_source": "Datu Iturria",
    "sidebar.variables": "Aldagaiak",
    "sidebar.plot_button": "Datuak Marraztu",
    "uploader.upload_csv": "CSV Igo",
    "uploader.import_analysis": "Analisia Inportatu",
    "uploader.new_table": "Taula Berria",
    "uploader.no_folder": "Ez da karpetarik ireki",
    "variables.independent": "Aldagai Askea (X)",
    "variables.dependent": "Mendeko Aldagaia (Y)",
    "main.workspace_title": "Azterketa Eremua",
    "main.workspace_description": "Igo CSV fitxategi bat edo inportatu analisi-saio bat hasteko.",
    "main.no_data": "Ez dago daturik erakusteko.",
    "main.plot_placeholder_title": "Marrazteko Prest",
    "main.plot_placeholder_description": "Hautatu zure aldagaiak eta egin klik 'Datuak Marraztu' botoian esploratzailean zure datuak ikusteko.",
    "tabs.analysis_fitting": "Analisia eta Doikuntza",
    "tabs.simulation": "Simulazioa",
    "tabs.close_tab_tooltip": "Itxi Fitxa",
    "simulation.title": "Simulazio Panela",
    "simulation.description": "Simulazio-ingurunea hemen egongo da eskuragarri. Zure datuekin modeloak probatu eta eszenatokiak exekutatu ahal izango dituzu.",
    "plot.observations": "Behaketak",
    "plot.regression_line": "Erregresio Lerroa",
    "tooltip.residual": "Hondarra",
    "analysis.show_grid": "Erakutsi Sarea",
    "analysis.show_line": "Erakutsi Erregresio Lerroa",
    "analysis.show_residuals": "Erakutsi Hondarrak",
    "analysis.show_observations": "Erakutsi Behaketak",
    "analysis.regression_type_title": "Erregresio Mota",
    "analysis.linear_regression": "Erregresio Lineala",
    "analysis.higher_order_regressions": "Goi Mailako Erregresioak",
    "analysis.regression_method_title": "Erregresio Metodoa",
    "analysis.regression_method_placeholder": "Hautatutako erregresiorako metodo-aukerak hemen agertuko dira.",
    "analysis.tab_analysis": "Analisia",
    "analysis.tab_residuals": "Hondarren Grafikoa",
    "analysis.residual": "Hondarra",
    "analysis.residuals": "Hondarrak",
    "analysis.controls_title": "Analisiaren Kontrolak",
    "analysis.decimal_points": "Puntu Hamartarrak",
    "plot_explorer.title": "Grafiko Esploratzailea",
    "plot_explorer.tab_series": "Serieak",
    "plot_explorer.tab_plot": "Grafikoa",
    "plot_explorer.tab_export": "Esportatu",
    "plot_explorer.general": "Orokorra",
    "plot_explorer.scatter": "Dispertsio Grafikoa",
    "plot_explorer.regression_line": "Erregresio Lerroa",
    "plot_explorer.residuals": "Hondarrak",
    "plot_explorer.color": "Kolorea",
    "plot_explorer.opacity": "Opakutasuna",
    "plot_explorer.size": "Tamaina",
    "plot_explorer.width": "Zabalera",
    "plot_explorer.style": "Estiloa",
    "plot_explorer.style_solid": "Solidoa",
    "plot_explorer.style_dashed": "Marratua",
    "plot_explorer.style_dotted": "Puntukatua",
    "plot_explorer.show_legend": "Erakutsi Legenda",
    "plot_explorer.show_title": "Erakutsi Izenburua",
    "plot_explorer.axes_domain": "Ardatzen Domeinua",
    "plot_explorer.x_min": "X Min",
    "plot_explorer.x_max": "X Max",
    "plot_explorer.y_min": "Y Min",
    "plot_explorer.y_max": "Y Max",
    "plot_explorer.tick_formatting": "Marken Formatua",
    "plot_explorer.sig_figs": "Zifra Esang.",
    "plot_exporter.title": "Esportazioaren Konfigurazioa",
    "plot_exporter.filename": "Fitxategi Izena",
    "plot_exporter.format": "Formatua",
    "plot_exporter.dimensions": "Neurriak",
    "plot_exporter.width": "Zabalera",
    "plot_exporter.height": "Altuera",
    "plot_exporter.dpi": "Ebazpena (DPI)",
    "plot_exporter.labels": "Etiketak",
    "plot_exporter.plot_title": "Grafikoaren Izenburua",
    "plot_exporter.x_axis_label": "X Ardatzaren Etiketa",
    "plot_exporter.y_axis_label": "Y Ardatzaren Etiketa",
    "plot_exporter.typography": "Tipografia",
    "plot_exporter.font_family": "Letra-tipoa",
    "plot_exporter.font_size": "Letra-tamaina (px)",
    "plot_exporter.theme": "Gaia",
    "plot_exporter.theme_current": "Oraingoa",
    "plot_exporter.theme_grayscale": "Gris-eskala",
    "plot_exporter.theme_publication": "Argitalpena",
    "plot_exporter.export_button": "Esportatu",
    "right_sidebar.equation": "Erregresio Ekuazioa",
    "results.summary": "Laburpen Estatistikak",
    "results.rsquared": "R-Karratua",
    "results.rsquared_desc": "Modelaren Doikuntza",
    "results.stderr": "Errore Estandarra",
    "results.stderr_desc": "Aurreikuspen Errorea",
    "results.slope": "Malda (β₁)",
    "results.slope_desc": "X-ren eragina Y-n",
    "results.intercept": "Abscisa (β₀)",
    "results.intercept_desc": "Y-ren balioa X=0 denean",
    "statusbar.ready": "Prest",
    "statusbar.error": "Errorea",
    "statusbar.rows": "Errenkadak",
    "statusbar.type": "Erregresio Lineala",
    "table.add_row": "Gehitu Errenkada",
    "table.add_column": "Gehitu Zutabea",
    "table.delete_row": "Ezabatu Errenkada",
    "table.delete_column": "Ezabatu Zutabea",
    "table.delete_selected_rows": "Ezabatu Hautatutako Errenkadak",
    "table.new_column_prompt": "Sartu zutabe berriaren izena:",
    "table.duplicate_column_error": "Dagoeneko badago '{columnName}' izeneko zutabe bat.",
    "error.invalid_file_type": "Fitxategi mota baliogabea. Mesedez, igo CSV fitxategi bat.",
    "error.not_enough_columns": "CSV fitxategiak gutxienez bi zutabe izan behar ditu.",
    "error.no_data_rows": "CSV fitxategiak ez du datu-errenkada baliodunik. Egiaztatu fitxategiaren edukia eta formatua.",
    "error.parse_failed": "Ezin izan da CSV fitxategia aztertu. Mesedez, egiaztatu formatua.",
    "error.import_failed": "Ezin izan da analisi-fitxategia inportatu. Baliteke hondatuta egotea edo formatu okerrean egotea.",
    "error.missing_data": "Mesedez, hautatu aldagaiak marraztu aurretik.",
    "error.same_variables": "Aldagai askea eta mendeko aldagaia ezin dira berdinak izan.",
    "error.analysis_failed": "Azterketak huts egin du: {errorMessage}",
    "error.unknown": "Errore ezezagun bat gertatu da.",
    "error.not_enough_data": "Ez dago datu-puntu baliozko nahikorik erregresio-analisirako (gutxienez 2 behar dira).",
    "error.identical_x": "Aldagai independenteko (X) balio guztiak berdinak dira. Ezin da erregresio-lerro bakarra kalkulatu."
  }
};


export const AppProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [theme, setThemeState] = useState<Theme>('dark');
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedTheme = localStorage.getItem('theme') as Theme;
    const savedLang = localStorage.getItem('language') as Language;

    const initialTheme = savedTheme || (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
    setTheme(initialTheme);
    
    const initialLang = savedLang || 'en';
    setLanguage(initialLang);

  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const setTheme = (newTheme: Theme) => {
    setThemeState(newTheme);
    localStorage.setItem('theme', newTheme);
    if (newTheme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  };

  const t = useCallback((key: string, replacements: { [key: string]: string } = {}) => {
    const translationSet = translations[language];
    let translatedString = translationSet ? (translationSet[key] || key) : key;
    
    Object.keys(replacements).forEach(placeholder => {
        translatedString = translatedString.replace(`{${placeholder}}`, replacements[placeholder]);
    });

    return translatedString;
  }, [language]);

  return (
    <AppContext.Provider value={{ theme, setTheme, language, setLanguage, t }}>
      {children}
    </AppContext.Provider>
  );
};

export const useAppContext = () => {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error('useAppContext must be used within an AppProvider');
  }
  return context;
};